name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        # Update Python versions to 3.10 or newer, as required by Django 5.x
        python-version: [3.10, 3.11, 3.12] # Recommended: Use actively supported Python versions

    steps:
    - uses: actions/checkout@v4
      # This action checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it.

    - name: Set up Python ${{ matrix.python-version }}
      # Using the latest stable version of setup-python action for better compatibility
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
      # This action sets up the specified Python version and adds it to the PATH.

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      # Installs project dependencies listed in requirements.txt.
      # It also upgrades pip to ensure you're using a recent version.

    - name: Run Tests
      run: |
        # Ensure Django's settings module is correctly set if needed for tests.
        # Replace 'your_project_name' with the actual name of your Django project's main directory
        # that contains settings.py (e.g., if your structure is my_repo/my_project/settings.py)
        export DJANGO_SETTINGS_MODULE=your_project_name.settings
        python manage.py test
      # Executes your Django test suite.
      # Make sure 'your_project_name' is replaced with the actual name of your Django project's
      # main directory (the one containing settings.py) for the DJANGO_SETTINGS_MODULE.
